language: java



install:
- mvn install

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - master

jobs:
  include:
  - stage: test
    jdk: openjdk8
    script:
    - mvn test -B -P coverage
    after_success:
    - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
    - bash <(curl -s https://codecov.io/bash)
  - stage: test
    jdk: openjdk11
    script:
    - mvn test -B
  - stage: test
    jdk: openjdk12
    script:
    - mvn test -B
